# Generated by Django 4.0 on 2022-01-03 18:13

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Имя категории')),
                ('photo', models.ImageField(default='empty.jfif', upload_to='photos/сcategory/%m/%d/', verbose_name='Фото Категорий')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано ?')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата оновления')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mainApp.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
