# Generated by Django 4.0 on 2022-01-03 20:32

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок товара')),
                ('subtitle', models.CharField(max_length=250, verbose_name='Под заголовок товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('photo', models.ImageField(upload_to='photos/goods/%m/%d/', verbose_name='Фото товара')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опулбиковано ?')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.category', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
