# Generated by Django 4.0 on 2022-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='photo',
            field=models.ImageField(default='empty.jfif', upload_to='photos/goods/%m/%d/', verbose_name='Фото товара'),
        ),
    ]
